### ISSUE TITLE
Refactor multiple category properties into a single enum for the `transaction` class

### ISSUE THREAD

**Issue by idea404** [PiparHQ/factory#2]
I noticed that the `transaction` class currently uses multiple boolean properties to represent its state. This can lead to undesired behavior, as more than one boolean could be set to true, causing confusion and potential issues in the rest of your code logic.

Instead, I'd recommend combining all these properties into a single enum-type field that denotes the state the class is in. Here's the current property set:

```rust 
            .position(|t| {
                t.transaction_id == transaction_id
                    && t.store_contract_id == store_contract_id
                    && t.buyer_contract_id == env::predecessor_account_id()
                    && t.approved == true
                    && t.shipped == true
                    && t.delivered == false
                    && t.disputed == false
                    && t.canceled == false
            })
```
https://github.com/PiparHQ/factory/blob/99a2586cce0ee7d3beb4094a032ae9afb93dad18/src/lib.rs#LL557C1-L561C43

A possible improvement could be:

```rust 
            .position(|t| {
                t.transaction_id == transaction_id
                    && t.store_contract_id == store_contract_id
                    && t.buyer_contract_id == env::predecessor_account_id()
                    && t.status == enum_class.APPROVED
            })
```

**Comment by kasodon** [comment]
Thanks for bringing this up @idea404, improvements have been made and they await your review. Please look through the recent changes and merge appropriately. Thanks!
